---
label: Project
hide_body: false
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: slug
  type: text
  config:
    required: true
  label: Slug
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: filter_labels
  type: tag_list
  default:
  - javascript
  - react
  - scss
  - css
  - styled components
  - html
  - gatsby
  - next
  - nextjs
  - vue
  - node
  - nodejs
  - apis
  label: Filter Labels
pages:
- projects/title.md
